"""remove field sr

Revision ID: 0d44cc6994fa
Revises: d8ead82d5400
Create Date: 2019-06-15 18:32:10.746289

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0d44cc6994fa'
down_revision = 'd8ead82d5400'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audit', 'sr')
    op.drop_column('favorites', 'sr')
    op.drop_column('user_category', 'sr')
    op.drop_column('users', 'sr')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sr', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('user_category', sa.Column('sr', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('favorites', sa.Column('sr', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('audit', sa.Column('sr', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
