"""change date to datetime

Revision ID: 3a386e09347a
Revises: 565b08cb1053
Create Date: 2019-06-15 15:21:34.773558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a386e09347a'
down_revision = '565b08cb1053'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
