"""add meta_data column to favorite thing

Revision ID: 565b08cb1053
Revises: e3fc8bdee72b
Create Date: 2019-06-15 10:12:13.451486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565b08cb1053'
down_revision = 'e3fc8bdee72b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('meta_data', sa.PickleType(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'meta_data')
    # ### end Alembic commands ###
