"""add created field to audits, users

Revision ID: d3cf596415fa
Revises: 0d44cc6994fa
Create Date: 2019-06-19 20:59:54.956776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3cf596415fa'
down_revision = '0d44cc6994fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'created')
    op.drop_column('audit', 'created')
    # ### end Alembic commands ###
