export const LOGIN = "LOGIN";
export const LOG_OUT = "LOG_OUT";

export const ADD_FAVORITE_THING = "ADD_FAVORITE_THING";
export const ADD_FAVORITE_CATEGORY = "ADD_FAVORITE_CATEGORY";
export const REPLACE_FAVORITE_THINGS = "REPLACE_FAVORITE_THINGS";
export const REPLACE_ALL_CATEGORIES_WITH_NEW_LIST =
  "REPLACE_ALL_CATEGORIES_WITH_NEW_LIST";
